# April Code pudding Project (Youtube Sentiment Analysis)

## Importing Libraries

In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
  
import seaborn as sns
import re
import os

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from wordcloud import WordCloud

import xgboost as xgb
from textblob import TextBlob

from tqdm import tqdm

In [110]:
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jeelf\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jeelf\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\jeelf\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

## Data Overview

In [111]:
dataset_path = os.path.join('..', 'datasets', 'archive')

comments = pd.read_csv(
    os.path.join(dataset_path, 'UScomments.csv'),
    on_bad_lines='skip',
    encoding='utf-8',
    low_memory=False
)
videos = pd.read_csv(
    os.path.join(dataset_path, 'USvideos.csv'), 
    on_bad_lines='skip', 
    encoding='utf-8')

In [112]:
comments = pd.read_csv(r'C:\Jeel Faldu\Data Scientist\Projects\april_code_jam_pudding\youtube_sentiment_analysis\datasets\archive\UScomments.csv', 
                       on_bad_lines='skip', 
                       encoding= 'utf-8', 
                       low_memory=False)

In [113]:
videos = pd.read_csv(r'C:\Jeel Faldu\Data Scientist\Projects\april_code_jam_pudding\youtube_sentiment_analysis\datasets\archive\USvideos.csv', 
                       on_bad_lines='skip', 
                       encoding= 'utf-8', 
                       low_memory=False)

In [114]:
display(comments.head(5)) # Display the first 5 rows of the comments DataFrame

,video_id,comment_text,likes,replies
0,XpVt6Z1Gjjo,Logan Paul it's yo big day ‼️‼️‼️,4,0
1,XpVt6Z1Gjjo,I've been following you from the start of your...,3,0
2,XpVt6Z1Gjjo,Say hi to Kong and maverick for me,3,0
3,XpVt6Z1Gjjo,MY FAN . attendance,3,0
4,XpVt6Z1Gjjo,trending 😉,3,0

In [115]:
display(videos.head(5)) # Display the first 5 rows of the videos DataFrame

,video_id,title,channel_title,category_id,tags,views,likes,dislikes,comment_total,thumbnail_link,date
0,XpVt6Z1Gjjo,1 YEAR OF VLOGGING -- HOW LOGAN PAUL CHANGED Y...,Logan Paul Vlogs,24,logan paul vlog|logan paul|logan|paul|olympics...,4394029,320053,5931,46245,https://i.ytimg.com/vi/XpVt6Z1Gjjo/default.jpg,13.09
1,K4wEI5zhHB0,iPhone X — Introducing iPhone X — Apple,Apple,28,Apple|iPhone 10|iPhone Ten|iPhone|Portrait Lig...,7860119,185853,26679,0,https://i.ytimg.com/vi/K4wEI5zhHB0/default.jpg,13.09
2,cLdxuaxaQwc,My Response,PewDiePie,22,[none],5845909,576597,39774,170708,https://i.ytimg.com/vi/cLdxuaxaQwc/default.jpg,13.09
3,WYYvHb03Eog,Apple iPhone X first look,The Verge,28,apple iphone x hands on|Apple iPhone X|iPhone ...,2642103,24975,4542,12829,https://i.ytimg.com/vi/WYYvHb03Eog/default.jpg,13.09
4,sjlHnJvXdQs,iPhone X (parody),jacksfilms,23,jacksfilms|parody|parodies|iphone|iphone x|iph...,1168130,96666,568,6666,https://i.ytimg.com/vi/sjlHnJvXdQs/default.jpg,13.09

In [116]:
videos.shape

(7992, 11)

In [117]:
comments.shape

(691400, 4)

In [118]:
comments.info() # Display information about the comments DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691400 entries, 0 to 691399
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   video_id      691400 non-null  object
 1   comment_text  691374 non-null  object
 2   likes         691400 non-null  object
 3   replies       691400 non-null  object
dtypes: object(4)
memory usage: 21.1+ MB

In [119]:
videos.info() # Display information about the videos DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7992 entries, 0 to 7991
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   video_id        7992 non-null   object
 1   title           7992 non-null   object
 2   channel_title   7992 non-null   object
 3   category_id     7992 non-null   int64
 4   tags            7992 non-null   object
 5   views           7992 non-null   int64
 6   likes           7992 non-null   int64
 7   dislikes        7992 non-null   int64
 8   comment_total   7992 non-null   int64
 9   thumbnail_link  7992 non-null   object
 10  date            7992 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 686.9+ KB

In [120]:
comments.describe() # Display descriptive statistics of the comments DataFrame

           video_id comment_text   likes replies
count        691400       691374  691400  691400
unique         2266       434075    1060     369
top     XpVt6Z1Gjjo          Lol       0       0
freq            800          310  563752  649366

In [121]:
videos.info() # Display information about the videos DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7992 entries, 0 to 7991
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   video_id        7992 non-null   object
 1   title           7992 non-null   object
 2   channel_title   7992 non-null   object
 3   category_id     7992 non-null   int64
 4   tags            7992 non-null   object
 5   views           7992 non-null   int64
 6   likes           7992 non-null   int64
 7   dislikes        7992 non-null   int64
 8   comment_total   7992 non-null   int64
 9   thumbnail_link  7992 non-null   object
 10  date            7992 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 686.9+ KB

In [122]:
comments.isna().sum() # Check for missing values in the comments DataFrame
comments.isna().sum()/len(comments) # Check for missing values in the comments DataFrame as a percentage

video_id        0.000000
comment_text    0.000038
likes           0.000000
replies         0.000000
dtype: float64

In [123]:
comments.dropna(subset=['comment_text'], inplace=True) # Drop rows with missing values in the 'comment_text' column

In [124]:
videos.isna().sum() # Check for missing values in the videos DataFrame

video_id          0
title             0
channel_title     0
category_id       0
tags              0
views             0
likes             0
dislikes          0
comment_total     0
thumbnail_link    0
date              0
dtype: int64

In [125]:
comments_duplicates = comments.duplicated().sum() # Check for duplicate rows in the comments DataFrame
display(comments_duplicates) # Display the number of duplicate rows in the comments DataFrame

219743

In [126]:
videos_duplicates = videos.duplicated().sum() # Check for duplicate rows in the comments DataFrame
display(videos_duplicates) # Display the number of duplicate rows in the comments DataFrame

0

In [127]:
def clear_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-z\s]","", text)
    text = text.split()
    return " ".join(text)

In [128]:
comments['clean_text'] = comments['comment_text'].astype(str).apply(clear_text) # Apply the clear_text function to the 'comment_text' column
comments= comments.drop(columns=['comment_text'])

In [129]:
display(comments.head(5)) # Display the first 5 rows of the comments DataFrame after cleaning

,video_id,likes,replies,clean_text
0,XpVt6Z1Gjjo,4,0,logan paul its yo big day
1,XpVt6Z1Gjjo,3,0,ive been following you from the start of your ...
2,XpVt6Z1Gjjo,3,0,say hi to kong and maverick for me
3,XpVt6Z1Gjjo,3,0,my fan attendance
4,XpVt6Z1Gjjo,3,0,trending

In [130]:
print(comments['clean_text'].isna().sum())  # Check for missing values

0

In [131]:
stop_words =  set(stopwords.words('english')) # Set of English stop words

In [132]:
lemmatizer = WordNetLemmatizer() # Initialize the lemmatizer

def lemmatize(text):
    tokens = word_tokenize(text.lower())
    tokens = [token for token in tokens if token not in stop_words]
    lemmas = [lemmatizer.lemmatize(token) for token in tokens]
    return " ".join(lemmas)

In [133]:
comments['lemmatize_text'] = comments['clean_text'].apply(lemmatize) # Apply the clear_text function to the 'comment_text' column
display(comments['lemmatize_text'].head(10))

0                                logan paul yo big day
1          ive following start vine channel seen vlogs
2                                 say hi kong maverick
3                                       fan attendance
4                                             trending
5                                    trending ayyeeeee
6                                           end though
7                                             trending
8                          happy one year vlogaversary
9    shit brother may single handedly ruined youtub...
Name: lemmatize_text, dtype: object

In [134]:
display(comments[['clean_text', 'lemmatize_text']].head(20)) # Display the first 5 rows of the comments DataFrame after cleaning

,clean_text,lemmatize_text
0,logan paul its yo big day,logan paul yo big day
1,ive been following you from the start of your ...,ive following start vine channel seen vlogs
2,say hi to kong and maverick for me,say hi kong maverick
3,my fan attendance,fan attendance
4,trending,trending
5,on trending ayyeeeee,trending ayyeeeee
6,the end though,end though
7,trending,trending
8,happy one year vlogaversary,happy one year vlogaversary
9,you and your shit brother may have single hand...,shit brother may single handedly ruined youtub...
10,there should be a mini logan paul too,mini logan paul
11,dear logan i really wanna get your merch but i...,dear logan really wan na get merch dont money ...
12,honestly evan is so annoying like its not funn...,honestly evan annoying like funny watching try...
13,casey is still better then logan,casey still better logan
14,aw geez rick this guy is the face of youtube,aw geez rick guy face youtube
15,he happy cause he in a movie,happy cause movie
16,ayyyyoooo logang what up this was a hard vlog ...,ayyyyoooo logang hard vlog watch logan dare de...
17,bro y didnt u give merch to johannes he is ur boy,bro didnt u give merch johannes ur boy
18,its been fun watching you grow im at days stra...,fun watching grow im day straight cant seem gr...
19,made a lot of people hate youtube gj,made lot people hate youtube gj

In [135]:
comments.shape

(691374, 5)

### Videos

In [136]:
videos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7992 entries, 0 to 7991
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   video_id        7992 non-null   object
 1   title           7992 non-null   object
 2   channel_title   7992 non-null   object
 3   category_id     7992 non-null   int64
 4   tags            7992 non-null   object
 5   views           7992 non-null   int64
 6   likes           7992 non-null   int64
 7   dislikes        7992 non-null   int64
 8   comment_total   7992 non-null   int64
 9   thumbnail_link  7992 non-null   object
 10  date            7992 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 686.9+ KB

In [137]:
videos['like_dislike_ratio'] = videos['likes'] / videos['dislikes'] # Calculate the like-dislike ratio
display(videos.head(5)) # Display the first 10 rows of the like-dislike ratio

,video_id,title,channel_title,category_id,tags,views,likes,dislikes,comment_total,thumbnail_link,date,like_dislike_ratio
0,XpVt6Z1Gjjo,1 YEAR OF VLOGGING -- HOW LOGAN PAUL CHANGED Y...,Logan Paul Vlogs,24,logan paul vlog|logan paul|logan|paul|olympics...,4394029,320053,5931,46245,https://i.ytimg.com/vi/XpVt6Z1Gjjo/default.jpg,13.09,53.962738
1,K4wEI5zhHB0,iPhone X — Introducing iPhone X — Apple,Apple,28,Apple|iPhone 10|iPhone Ten|iPhone|Portrait Lig...,7860119,185853,26679,0,https://i.ytimg.com/vi/K4wEI5zhHB0/default.jpg,13.09,6.966266
2,cLdxuaxaQwc,My Response,PewDiePie,22,[none],5845909,576597,39774,170708,https://i.ytimg.com/vi/cLdxuaxaQwc/default.jpg,13.09,14.496832
3,WYYvHb03Eog,Apple iPhone X first look,The Verge,28,apple iphone x hands on|Apple iPhone X|iPhone ...,2642103,24975,4542,12829,https://i.ytimg.com/vi/WYYvHb03Eog/default.jpg,13.09,5.498679
4,sjlHnJvXdQs,iPhone X (parody),jacksfilms,23,jacksfilms|parody|parodies|iphone|iphone x|iph...,1168130,96666,568,6666,https://i.ytimg.com/vi/sjlHnJvXdQs/default.jpg,13.09,170.186620

## Creating Sentiment Feature

In [138]:
def get_sentiment(text):
    return TextBlob(text).sentiment.polarity # Function to get the sentiment polarity of a text 

comments['sentiment_score'] = comments['lemmatize_text'].apply(get_sentiment) # Apply the get_sentiment function to the 'lemmatize_text' column
comments['sentiment_label'] = comments['sentiment_score'].apply(lambda x: 'positive' if x > 0 else 'negative') # Assign sentiment labels based on the sentiment score

In [139]:
sentiment_summary = comments.groupby('video_id')['sentiment_label'].value_counts(normalize=True).unstack().fillna(0) # Group by video_id and calculate the sentiment label counts
sentiment_summary['comment_sentiment_ratio'] = sentiment_summary['positive'] / sentiment_summary['negative'] # Calculate the comment sentiment ratio

In [140]:
cv = videos.merge(sentiment_summary[['comment_sentiment_ratio']], on='video_id', how='inner') # Merge the sentiment summary with the videos DataFrame

In [141]:
display(cv.head(5)) # Display the first 5 rows of the merged DataFrame

,video_id,title,channel_title,category_id,tags,views,likes,dislikes,comment_total,thumbnail_link,date,like_dislike_ratio,comment_sentiment_ratio
0,XpVt6Z1Gjjo,1 YEAR OF VLOGGING -- HOW LOGAN PAUL CHANGED Y...,Logan Paul Vlogs,24,logan paul vlog|logan paul|logan|paul|olympics...,4394029,320053,5931,46245,https://i.ytimg.com/vi/XpVt6Z1Gjjo/default.jpg,13.09,53.962738,0.408451
1,cLdxuaxaQwc,My Response,PewDiePie,22,[none],5845909,576597,39774,170708,https://i.ytimg.com/vi/cLdxuaxaQwc/default.jpg,13.09,14.496832,0.501880
2,WYYvHb03Eog,Apple iPhone X first look,The Verge,28,apple iphone x hands on|Apple iPhone X|iPhone ...,2642103,24975,4542,12829,https://i.ytimg.com/vi/WYYvHb03Eog/default.jpg,13.09,5.498679,0.503759
3,sjlHnJvXdQs,iPhone X (parody),jacksfilms,23,jacksfilms|parody|parodies|iphone|iphone x|iph...,1168130,96666,568,6666,https://i.ytimg.com/vi/sjlHnJvXdQs/default.jpg,13.09,170.186620,0.544402
4,cMKX2tE5Luk,The Disaster Artist | Official Trailer HD | A24,A24,1,a24|a24 films|a24 trailers|independent films|t...,1311445,34507,544,3040,https://i.ytimg.com/vi/cMKX2tE5Luk/default.jpg,13.09,63.431985,0.643192

In [142]:
cv[['like_dislike_ratio', 'comment_sentiment_ratio']].corr()

                         like_dislike_ratio  comment_sentiment_ratio
like_dislike_ratio                 1.000000                 0.268627
comment_sentiment_ratio            0.268627                 1.000000

In [143]:
cv['ratio_diff'] = cv['like_dislike_ratio'] - cv['comment_sentiment_ratio'] # Calculate the difference between the like-dislike ratio and the comment sentiment ratio
cv.sort_values('ratio_diff', ascending=False).sample(5) # Sort the DataFrame by the ratio difference in descending order

,video_id,title,channel_title,category_id,tags,views,likes,dislikes,comment_total,thumbnail_link,date,like_dislike_ratio,comment_sentiment_ratio,ratio_diff
6206,DUMEmGUc7yc,Behind the Sides,vlogbrothers,22,education|vlog|theater|tour|music|entertainmen...,123190,7626,72,890,https://i.ytimg.com/vi/DUMEmGUc7yc/default.jpg,15.10,105.916667,1.117021,104.799645
1087,bAdqazixuRY,AUTOMATICA 4k - Robots Vs. Music - Nigel Stanford,Nigel John Stanford,10,[none],158834,6712,41,580,https://i.ytimg.com/vi/bAdqazixuRY/default.jpg,18.09,163.707317,1.777778,161.929539
7358,7KbjNfCV-lY,I Dressed Like It Was 1987,Safiya Nygaard,22,i dressed like it was 1987|1987|1987 fashion|8...,2485566,137268,1305,17739,https://i.ytimg.com/vi/7KbjNfCV-lY/default.jpg,21.10,105.186207,1.127660,104.058547
4636,TOI9DKsWMx4,Slide Fire - How it works,No Surrender Productions,1,slide fire stock|bump fire|full auto|AR15|AK47,83634,52,42,52,https://i.ytimg.com/vi/TOI9DKsWMx4/default.jpg,6.10,1.238095,2.250000,-1.011905
2800,jzaRIWMxz0Y,Hyperlapse DC,max berger,22,dc|hyperlapse|time lapse|fuji|xt10|sound desig...,143788,1632,61,85,https://i.ytimg.com/vi/jzaRIWMxz0Y/default.jpg,27.09,26.754098,1.823529,24.930569

### Model Training

In [144]:
X_train, X_test, y_train, y_test = train_test_split(
    comments['lemmatize_text'], 
    comments['sentiment_label'],
    test_size=0.2, random_state=7
)

In [145]:
vectorizer = TfidfVectorizer() # Initialize the TfidfVectorizer
X_train_vectorized = vectorizer.fit_transform(X_train) # Fit and transform the training data
X_test_vectorized = vectorizer.transform(X_test) # Transform the test data

In [146]:
model = LogisticRegression() # Initialize the Logistic Regression model
model.fit(X_train_vectorized, y_train) # Fit the model to the training data

LogisticRegression()

In [147]:
y_pred = model.predict(X_test_vectorized) # Make predictions on the test data

In [149]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9719038148616886
[[78723  1475]
 [ 2410 55667]]
              precision    recall  f1-score   support

    negative       0.97      0.98      0.98     80198
    positive       0.97      0.96      0.97     58077

    accuracy                           0.97    138275
   macro avg       0.97      0.97      0.97    138275
weighted avg       0.97      0.97      0.97    138275

### CatBoost Model

In [150]:
from catboost import CatBoostClassifier

In [151]:
X = vectorizer.transform(comments['lemmatize_text']) # Transform the entire dataset
y = comments['sentiment_label'].map({"negative":0, "positive": 1}) # Target variable

In [152]:
valid_mask = y.notna()
X = X[valid_mask.to_numpy()] # Filter the feature matrix based on the valid mask
y = y[valid_mask] # Filter the target variable based on the valid mask

In [153]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=7
) # Split the data into training and test sets

In [157]:
cat = CatBoostClassifier(iterations=200, depth=6, learning_rate=0.1, loss_function='Logloss', eval_metric='Accuracy', random_seed=7, verbose=0) # Initialize the CatBoostClassifier
cat.fit(X_train, y_train) # Fit the model to the training data

In [158]:
y_pred_cat = cat.predict(X_test) # Make predictions on the test data

print("Accuracy:", accuracy_score(y_test, y_pred_cat)) # Print the accuracy of the model
print(confusion_matrix(y_test, y_pred_cat)) # Print the confusion matrix
print(classification_report(y_test, y_pred_cat)) # Print the classification report

Accuracy: 0.9211281865847044
[[77250  2948]
 [ 7958 50119]]
              precision    recall  f1-score   support

           0       0.91      0.96      0.93     80198
           1       0.94      0.86      0.90     58077

    accuracy                           0.92    138275
   macro avg       0.93      0.91      0.92    138275
weighted avg       0.92      0.92      0.92    138275